[package]
name = "bitcoin-rust-explore"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
bitcoin = "0.32.8"
bitcoincore-rpc = "0.19.0"
serde = { version = "1.0.228", features = ["derive"] }
